# Do not use this file because it is used as a template to run python scripts. Without this file, users cannot debug fatal crashes.
import traceback
import sys
import os
# from gym_TAIL import SocketRegister
from threading import Thread
import sys
import time
import signal


def keyboardInterruptHandler(signal, frame):
    print("KeyboardInterrupt (ID: {}) has been caught. Cleaning up...".format(signal))
    try:
        sys.exit(0)
    except SystemExit:
        os._exit(0)

signal.signal(signal.SIGINT, keyboardInterruptHandler)

# def auto_flush():
#     while True:
#         sys.stdout.flush()
#         sys.stderr.flush()
#         sys.stdin.flush()
#         time.sleep(1/1000)
#
#
# flush_thread = Thread(target=auto_flush)
# flush_thread.setDaemon(True)
# flush_thread.start()






"""
This file is auto generated by running PythonOptimizationEngine.
"""
try:
    #INJECT

except Exception as err:
    print("caught error")
#     errors = traceback.TracebackException.from_exception(err).format()
#     tb = ''.join(errors)
#     print("caught error")
#     print(tb)
# #     SocketRegister.get(0).send(message=tb, channel="$ISSUE")
# #     SocketRegister.get(0).disconnect()
#     try:
#         sys.exit(0)
#     except SystemExit:
#         os._exit(0)
